### PR TITLE
Fix: Allow gulp tasks to exit

### LINKED ISSUE #2: gulp task doesn't exit
Gulp version: 3.8.10

My task:

```
gulp.task('styleguide', function(callback) {
  return gulp.src('clients/boss/less/*.less')
    .pipe(dss({
      output: 'styleguide.html',
      //templatePath: path.join(__dirname, 'templates')
    }))
    .pipe(gulp.dest('dist/boss'));
});
```

The task completes but I have to Ctrl+C to get my prompt back (Ubuntu 14.04)

### PR DESCRIPTION
**Pull request by gustavpursche**
Fixes #2 

Next step could be, to passing the nunjucks options into the plugin function. What do you think about this?

### CODE REVIEW

**Comment by jaysoo** [comment]
@gustavpursche Thanks! :)

**Comment by gustavpursche** [comment]
@jaysoo Wow, that was quick :) Could you also create a new npm release that fast?

**Comment by jaysoo** [comment]
Published as `0.1.1`.

**Comment by gustavpursche** [comment]
:boom: :+1:

**Pull request merged**
